#!/usr/bin/env node
/**
 * Prose linter for the Markdown in this repo.
 *
 * Ported from the fonbnk codebase wiki's `wiki-lint.js --style`, whose rules are
 * written up under "Do not write slop" and "Write in ASD-STE100 Simplified
 * Technical English". The short version: one fact per sentence, no em dash
 * joining two clauses, no stacked brackets, no slash meaning "or", no hedge
 * words, no sweeping claim you did not check, active voice.
 *
 * It reads prose only. Frontmatter, fenced code, tables, headings and HTML
 * comments are dropped first, inline code and link targets collapse to one
 * token, and a long quotation is blanked, because quoting someone accurately is
 * not a style error.
 *
 * Usage:
 *   node scripts/prose-lint.mjs                 # every .md outside node_modules
 *   node scripts/prose-lint.mjs README.md       # one file
 *   node scripts/prose-lint.mjs --verbose       # every finding, not a sample
 *   node scripts/prose-lint.mjs --summary       # per-file totals only
 */
import { readdirSync, readFileSync, statSync } from 'node:fs'
import { join, relative, sep } from 'node:path'

const ROOT = process.cwd()
const SKIP_DIRS = new Set(['node_modules', 'dist', '.git'])
/** Generated by changesets. Rewriting it would be undone on the next release. */
const SKIP_FILES = /(^|[\\/])CHANGELOG\.md$/

const EM_DASH_PER_1000 = 3
const MAX_SENTENCE_WORDS = 30
const MAX_BRACKETS_PER_SENTENCE = 1

const HEDGES =
  /\b(just|simply|actually|really|essentially|basically|genuinely|honestly|literally|truly|fundamentally|inherently|inevitably|arguably|notably|crucially|importantly|interestingly|effectively)\b/gi
const EXTREMES = /\b(always|never|every single|nobody|everyone|everybody)\b/gi
const BANNED = [
  [/\b(it is|it's) worth (noting|mentioning)\b/gi, 'state the fact directly'],
  [/\bnote that\b/gi, 'state the fact directly'],
  [/\bhere('s| is) (the thing|what|why|how|the problem)\b/gi, 'throat-clearing; cut it'],
  [/\bthe (truth|reality) is\b/gi, 'throat-clearing; cut it'],
  [/\bthis matters because\b/gi, 'say what breaks instead'],
  [/\bin this (section|page) (we|you)\b/gi, 'the heading already says it'],
  [/\bnot (just|only|merely|simply)\b[^.\n]{0,60}?\bbut\b/gi, 'write "X and Y"'],
  [
    /\b(is|are|was|were)n't\b[^.\n]{0,60}?(,|\.)\s*(it'?s|it is|they'?re|that'?s)\b/gi,
    'say what it is; do not say what it is not first',
  ],
  [
    /\b(the (data|code|system|design|schema|architecture|decision)) (tells|says|wants|knows|decides|believes|cares)\b/gi,
    'name the function that does it',
  ],
  [
    /\b(leverage|robust|seamless|streamline|unpack|deep dive|landscape|holistic|paradigm|game.chang\w+)\b/gi,
    'use a plain word',
  ],
]

function toProse(text) {
  const collapsed = text.replace(/"[^"]{25,600}?"/g, (m) => {
    const nl = (m.match(/\n/g) || []).length
    return m.includes('```') || nl > 4 ? m : `QUOTE${'\n'.repeat(nl)}`
  })
  const lines = collapsed.split(/\r?\n/)
  const out = []
  let inFence = false
  let inFrontmatter = lines[0] !== undefined && lines[0].trim() === '---'
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]
    if (inFrontmatter) {
      if (i > 0 && line.trim() === '---') inFrontmatter = false
      out.push('')
      continue
    }
    if (/^\s*```/.test(line)) {
      inFence = !inFence
      out.push('')
      continue
    }
    if (inFence || /^\s*\|/.test(line) || /^\s*#{1,6}\s/.test(line) || /^\s*<!--/.test(line)) {
      out.push('')
      continue
    }
    out.push(
      line
        .replace(/`[^`\n]*`/g, 'CODE')
        .replace(/!?\[([^\]]*)\]\([^)]*\)/g, '$1')
        // A file name is not prose. A page linking to a path with "never" in it
        // must not be charged for that word.
        .replace(/\b[\w.@/-]*\.(md|tsx?|m?js|cjs|json|ya?ml|sh|html|css)\b/g, 'FILE')
        // A quotation is someone else's words. Only long spans count; a short
        // scare quote is the page's own voice and stays in scope.
        .replace(/"[^"\n]{25,}"/g, 'QUOTE')
        .replace(/^\s*[-*+]\s+/, '')
        .replace(/^\s*\d+\.\s+/, '')
        // A list label may keep its dash. Turn it into a colon so the
        // clause-join check below does not count it.
        .replace(/^((?:\*\*[^*]{1,60}\*\*|CODE)(?:\s*\/\s*CODE)*)\s+—\s+/, '$1: '),
    )
  }
  return out
}

const ABBREV = /(e\.g|i\.e|etc|vs|cf|approx|Dr|Mr|Ms|no|No)\.$/
function sentences(line) {
  const parts = []
  let buf = ''
  for (const tok of line.split(/(\s+)/)) {
    buf += tok
    if (
      /[.!?]["')\]]?$/.test(tok.trim()) &&
      !ABBREV.test(tok.trim()) &&
      !/\d\.$/.test(tok.trim())
    ) {
      parts.push(buf.trim())
      buf = ''
    }
  }
  if (buf.trim()) parts.push(buf.trim())
  return parts.filter(Boolean)
}

const countOf = (s, re) => (s.match(re) || []).length
const clip = (s, n = 72) => (s.length > n ? `${s.slice(0, n - 1)}…` : s)

function styleReport(rel, text) {
  const proseLines = toProse(text)
  const findings = []
  let words = 0
  let emDash = 0
  for (let i = 0; i < proseLines.length; i++) {
    const line = proseLines[i]
    if (!line.trim()) continue
    const lineNo = i + 1
    words += line.split(/\s+/).filter(Boolean).length
    for (const s of sentences(line)) {
      const w = s.split(/\s+/).filter(Boolean).length
      const joins = countOf(s, /\S\s*—\s*\S/g)
      emDash += joins
      if (joins) findings.push([lineNo, 'em-dash', `${joins} clause-joining - ${clip(s)}`])
      if (w > MAX_SENTENCE_WORDS)
        findings.push([lineNo, 'long-sentence', `${w} words - ${clip(s)}`])
      const brackets = countOf(s, /\([^)]*\)/g)
      if (brackets > MAX_BRACKETS_PER_SENTENCE)
        findings.push([lineNo, 'stacked-brackets', `${brackets} bracket groups - ${clip(s)}`])
      for (const m of s.match(HEDGES) || []) findings.push([lineNo, 'hedge', `"${m}"`])
      for (const m of s.match(EXTREMES) || [])
        findings.push([lineNo, 'lazy-extreme', `"${m}" - say where you checked`])
      if (/\w\s+\/\s+\w/.test(s)) findings.push([lineNo, 'slash-or', `write "or" - ${clip(s)}`])
      for (const [re, fix] of BANNED) {
        for (const m of s.match(re) || [])
          findings.push([lineNo, 'banned', `"${clip(m, 40)}" -> ${fix}`])
      }
    }
  }
  const budget = Math.floor((words / 1000) * EM_DASH_PER_1000)
  return { rel, words, emDash, budget, overBudget: emDash > budget, findings }
}

function walk(dir, acc = []) {
  for (const name of readdirSync(dir)) {
    if (SKIP_DIRS.has(name)) continue
    const p = join(dir, name)
    if (statSync(p).isDirectory()) walk(p, acc)
    else if (name.endsWith('.md') && !SKIP_FILES.test(p)) acc.push(p)
  }
  return acc
}

const argv = process.argv.slice(2)
const verbose = argv.includes('--verbose')
const summary = argv.includes('--summary')
const only = argv.filter((a) => !a.startsWith('-'))
const files = only.length ? only.map((p) => join(ROOT, p)) : walk(ROOT)

const reports = files
  .map((p) => styleReport(relative(ROOT, p).split(sep).join('/'), readFileSync(p, 'utf8')))
  .sort((a, b) => b.findings.length - a.findings.length)

let total = 0
const byKind = new Map()
for (const r of reports) {
  total += r.findings.length
  for (const [, kind] of r.findings) byKind.set(kind, (byKind.get(kind) || 0) + 1)
  if (!r.findings.length && !r.overBudget) continue
  if (summary) {
    console.log(
      `${String(r.findings.length).padStart(4)}  ${r.rel}  (${r.words}w, em-dash ${r.emDash}/${r.budget}${r.overBudget ? ' OVER' : ''})`,
    )
    continue
  }
  console.log(
    `\n${r.rel}  (${r.words} words, em-dash ${r.emDash}/${r.budget}${r.overBudget ? ' OVER' : ''})`,
  )
  for (const [line, kind, msg] of verbose ? r.findings : r.findings.slice(0, 8)) {
    console.log(`  ${String(line).padStart(5)}  ${kind.padEnd(17)} ${msg}`)
  }
  if (!verbose && r.findings.length > 8) console.log(`  ... ${r.findings.length - 8} more`)
}

const failing = reports.filter((r) => r.findings.length || r.overBudget).length
const over = reports.filter((r) => r.overBudget).length
console.log(
  `\nprose-lint: ${reports.length} files - ${failing} with findings (${over} over the em-dash budget) - ${total} finding(s)`,
)
console.log(
  [...byKind.entries()]
    .sort((a, b) => b[1] - a[1])
    .map(([k, n]) => `  ${k}: ${n}`)
    .join('\n'),
)
